---
  plugins:
    - react
  extends:
    - airbnb/base
    - plugin:react/recommended
  parserOptions:
    ecmaFeatures:
      jsx: true
  globals:
     window: true
     location: true
     document: true
  rules:
    strict: off # turn this on once node and chai support it properly
    no-underscore-dangle: off
    no-multiple-empty-lines: ["error", {max: 1}]
    max-depth: error
    max-len: error
    complexity: error
    max-lines: error
    no-console: off # until a real logger is used
